# Generated by Django 4.1.7 on 2023-04-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(default='test', upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='cars',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cars',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
