# Generated by Django 4.1.7 on 2023-04-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_cars_options_cars_image_cars_is_reserved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(default='no image', upload_to='item_images'),
        ),
    ]
