# Generated by Django 4.1.7 on 2023-04-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_types_alter_cars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='categories',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.types'),
        ),
    ]
